version: '3.7'

services:
 pg:
  image: postgres:14
  ports:
   - "7432:5432"
  container_name: pg
  environment:
    POSTGRES_USER       : postgres
    POSTGRES_PASSWORD   : postgres

 comision:
  #image: siudocker/php:8.1-web-v1.0.3
  #container_name: comision
  build:
    context: .
    dockerfile: docker/Dockerfile
  ports:
   - "7008:8080"
  environment:
    DOCKER_NAME                       : comision
    DOCKER_WEB_PORT                   : 7008
    TOBA_PASS                         : toba
    TOBA_BASE_PASS                    : postgres
    TOBA_INSTALACION_DIR              : /usr/local/proyectos/comision/vendor/siu-toba/framework/instalacion
    TOBA_BASE_HOST                    : pg
    TOBA_BASE_NOMBRE                  : toba_comision
    TOBA_PROYECTO                     : comision
    TOBA_PROYECTO_DIR                 : /usr/local/proyectos/comision
    TOBA_PROYECTO_ALIAS               : /solicitudes
    TOBA_PROYECTO_INSTALAR            : "True"
    TOBA_INSTALAR_REFERENCIA          : "false"
    TOBA_INSTALAR_USUARIOS            : "True"
  links:
   - pg
  volumes:
   - E:/Users/Guarani Prod/code/proyectos:/usr/local/proyectos
   #- ./instalacion:/var/local/docker-data/comision-instalacion
